version: "3.8"

services:
  app:
    build: .
    image: vlts-tenant-server:v3
    container_name: vlts-tenant-server
    ports:
      - "5000:3006"
    env_file:
      - .env
    restart: unless-stopped